import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/layout";
import FloatingWhatsapp from "@/components/widgets/floating-whatsapp";
import { AppProviders } from "@/core/providers/app-providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`antialiased bg-[#0c0c0c]`}
      >
        <AppProviders>
          <MainLayout>
            {children}
          </MainLayout>
          <FloatingWhatsapp />
        </AppProviders>
      </body>
    </html>
  );
}
