import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/layout";
import FloatingWhatsapp from "@/components/widgets/floating-whatsapp";
import { AppProviders } from "@/core/providers/app-providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`antialiased bg-[#0c0c0c]`}
      >
        <AppProviders>
          <MainLayout>
            {children}
          </MainLayout>
          <FloatingWhatsapp />
        </AppProviders>


        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Preschool",
              name: "مدرسة هوكاه نوبيل",
              description:
                "حضانة وتعليم مبكر تهتم بتنمية مهارات الأطفال في بيئة آمنة وممتعة.",
              address: {
                "@type": "PostalAddress",
                addressCountry: "SA",
              },
              telephone: "+966 56 444 5555",
              url: "https://hookahnobel.com",
            }),
          }}
        />
      </body>
    </html>
  );
}
